### ISSUE TITLE
Color glitching while using intellisense feature

### ISSUE THREAD

**Issue by felixfong227** [ann-liu/1987-color-theme#1]
![image](https://user-images.githubusercontent.com/13918481/48752283-6ad63080-ecc3-11e8-86f8-0e79c1c30afe.png)

Overall the theme color looks ⭐️ 👍 

But once it gets into the intellisense selection box, it sure looks a little bit funny

**Comment by ann-liu** [comment]
Just published a fix for this, it should look better now :grinning: good catch, thanks!

<img width="485" alt="screen shot 2018-11-20 at 12 13 29 am" src="https://user-images.githubusercontent.com/33971145/48760490-eea80280-ec5a-11e8-9de9-bebd0c25f505.png">

**Comment by felixfong227** [comment]
Awesome @ann-liu 

Thanks 🎉
